name: NuMojo Unit Tests
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  testing-numojo:
    name: with ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-14"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Modular installer
        run: |
          curl -s https://get.modular.com | sh -

      - name: Install Mojo
        run: |
          modular install mojo
          pip install numpy

      - name: Set path Mojo
        shell: bash
        run: |
          echo "MODULAR_HOME=/home/runner/.modular" >> $GITHUB_ENV
          echo "/home/runner/.modular/pkg/packages.modular.com_mojo/bin"  >> $GITHUB_PATH

      - name: Run tests
        shell: bash
        run: |
          mojo test tests -I .